<script setup lang="ts">
import type { IProduct } from '@/models/common/types'
import { ShoppingBasketIcon } from 'lucide-vue-next'
import { defineProps } from 'vue'
import { useCartStore } from '@/stores/cart'
import { useRouter } from 'vue-router'

interface props {
  product: IProduct
}

const router = useRouter()
const props = defineProps<props>()
const { product } = props
const store = useCartStore()
const { addToCart } = store

const handleClick = () => {
  router.push(`/products/${product.autogeneratedSlug}`)
}

const handleAddToCart = (event: MouseEvent) => {
  event.stopPropagation()
  addToCart(product)
}
</script>
<template>
  <section
    @click="handleClick"
    class="w-72 h-[525px] cursor-pointer hover:shadow-lg border border-gray-200 p-4 grid"
  >
    <img :src="product.imageUrl" :alt="product.name" />
    <h3>{{ product.name }}</h3>
    <p class="font-bold">{{ product.defaultDisplayedPriceFormatted }}</p>
    <button
      @click="handleAddToCart"
      class="float-right bg-primary cursor-pointer flex justify-center items-center gap-2 hover:bg-teal-300"
    >
      <ShoppingBasketIcon /> Add to cart
    </button>
  </section>
</template>
