export interface ICategory {
  id: number
  name: string
  autogeneratedSlug: string
}

export interface IProduct {
  id: number
  name: string
  autogeneratedSlug: string
  price: number
  defaultDisplayedPriceFormatted: string
  imageUrl: string
  description: string
}
