<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { useCategoriesStore } from '@/stores/categories'
import { storeToRefs } from 'pinia'

const store = useCategoriesStore()

const { categories, isLoading } = storeToRefs(store)
</script>

<template>
  <div>
    <nav>
      <ul class="flex space-x-10">
        {{
          isLoading ? '...' : ''
        }}
        <li v-for="category in categories" :key="category.id">
          <RouterLink
            :to="`/category/${category.autogeneratedSlug}`"
            class="bottom-line"
            active-class="font-bold"
          >
            {{ category.name }}
          </RouterLink>
        </li>
      </ul>
    </nav>
  </div>
</template>
